// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkFinder.Models;

namespace ParkFinder.Migrations
{
    [DbContext(typeof(ParkFinderContext))]
    [Migration("20210125032939_AddUserClass")]
    partial class AddUserClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkFinder.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("ParkName")
                        .IsRequired();

                    b.Property<string>("ParkType")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<string>("Status");

                    b.Property<string>("Website");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            City = "Crater Lake",
                            ParkName = "Crater Lake",
                            ParkType = "National Park",
                            State = "OR",
                            Status = "Open",
                            Website = "https://www.nps.gov/crla/index.htm"
                        },
                        new
                        {
                            ParkId = 2,
                            City = "Batsto",
                            ParkName = "New Jersey Pinelands",
                            ParkType = "National Reserve",
                            State = "NJ",
                            Status = "Open",
                            Website = "https://www.nps.gov/pine/index.htm"
                        });
                });

            modelBuilder.Entity("ParkFinder.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
